### ISSUE TITLE
Overcome api limitations 

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/droid-hole#26]
Hi,

As the api has many limitations, would it not be possible to use the same Web request which the Web interface would use? Or do misunderstand something :D

Best regards
Hyper

**Comment by JGeek00** [comment]
The web admin panel is a PHP application. Some parts of the application rely on the API, but some others don't. I considered some time ago to implement on the app features that are only available on the web admin panel, but I discarded that option because it can create other issues because you are trying to do something that's not "officially" supported. 
I also created a client for AdGuard Home, and the Pi-hole API is just bullshit in comparison with AdGuard Home's one. The Pi-hole team seems to have put very little effort on the API, and seems that they won't improve it. It has very little documentation, it lacks a lot of features that the web admin panel has, and for me it's much more easy to work with the AdGuard Home API (also the AdGuard Home web admin panel is much better than the Pi-hole one).
From my point of view, I would recommend you switching to AdGuard Home.

**Comment by HyperCriSiS** [comment]
OK, I see. Sometime ago I testet Adguard but I do not remember why I decided to stay at Pi-hole.
There are some strange responsible people at Pi-hole. 
They are not eager to improve a lot of things, which are urgently needed I think. The Pi-hole log sucks so much.
It is often impossible to find the address that needs to be unblocked, because you have no possibilities to filter the log properly.
Maybe I should really give Adguard another try :+1:

Did you have both running for a while and if yes, is there anything you miss in Adguard which you had in Pi-Hole?

**Comment by JGeek00** [comment]
For example the Pi-hole statistics are better than AdGuard Home ones. It gives you more data and more information. But if we talk about features and product quality I prefer AdGuard Home. The quality of the web admin UI and the API is much better than Pi-hole. For example, setting up DoT and DoH on AdGuard Home is easier.
