### ISSUE TITLE
Publish on F-Droid or IzzyOnDroid

### ISSUE THREAD

**Issue by skyhoppertv** [JGeek00/droid-hole#47]
Hey, 
I think it would be really cool to get DroidHole from F-Droid or IzzyOnDroid, so you don't have to keep watching on GitHub for new updates or use Google Services. Would that be possible? 
I really love the App and this would make it even better ;D.

Regards
Mats

**Comment by JGeek00** [comment]
Hi. I have received that request before, but I discarded it because it would be another place to maintain the app updated, and currently I have so many apps available on so many places. On the AdGuard Home app I have a system that shows an alert on the app when there is an update available, but I think that's not implemented here.
